# IceBoatRacing Configuration

settings:
  checkpoint-radius: 25.0
  # Paste your Discord Webhook URL below to enable result posting.
  # Leave empty "" to disable.
  discord-webhook-url: ""

music:
  enabled: true
  # The sound key from your resource pack (sounds.json)
  sound-name: "minecraft:coconutmallmariokartwiiostfourone" # or any music you want
  # How long is the song in seconds? The plugin will re-play it after this time.
  loop-duration-seconds: 180
  volume: 1000.0
  pitch: 1.0

arenas:
# Data is saved here automatically